def doesCircleExist(commands):
    # Write your code here
    finalResult=[]
    print(commands)

    for command in commands:
        x,y=0,0
        posN=1
        posE=2
        posS=3
        posW=4
        position =0

        infiniteCommand= 4*command

        for item in range(len(infiniteCommand)):

            if infiniteCommand[item].lower() == 'l':
                position = (4+position-1)%4
            elif infiniteCommand[item].lower() == 'r':
                position =(position+1)%4
            else:
                if position == posE :
                    x+=1
                elif position == posS :
                     y-=1
                elif position == posN:
                    y+=1
                else:
                    x-=1
        if x ==0 and y==0:
            finalResult.append('YES')
        else:
            finalResult.append('NO')
    return finalResult

                







print(doesCircleExist(['LRLLLGRRRGGLRLLLGLLRLLLLGGLRLLLLLLRRLRGRGRRRLRGRRGGGLGGRLLLRLRLRRLLGGRLGLRLRLLLRLLLRLLGLRRRLLLRGRRLLLLLRRLRRRRLRLRLLLRLRGLLGRGRGLGRLRLGLLRLRLLGRGLGLRGRRLLRRLLLLLLLLLRRLGGRRLRGLRGLRGRGLLGLRRRRGRRGGGRLGLLRLRLLLLGLLLRGRRRRRGRLRRRRRRGLLGLLRRGLGGLGGGLRLLRGLGRRLGRRGRLGLLRRLRRLGRGGLRLLGRRLLLRRLRGLRLRLLLRLLLRLRGRRGRRLRLGRLRRRGGRLRGGLLRLLGRGLLLRGGLLLGRRLLLGRLLLLLRGGGRLGLRRLLGRRLGRGGLRRLRGLRLLRRLLLGRLLLLLGRRRRRGLRLRRLRLRRRLLLLLRRLGGLRRLLLLGRLLGLRGRRGLLLLRLRRLLGGRRRLLRLLRGRGLGLGRRLLLGLRLLLLLLGRGLLRRLLRRLGLLGGGRLRRRGRRRLGLGLLLLLLLLRLLRLLRGRGRRGGGLRLLRRRLRLLRRRRGLRRLRLGRLLGLRRLLRGRGLGGRRLRGGLRGGRLLLLRLLGLGRGRGLRRRRLLGLGLLGGRLLRLRLLRLRRLLLRGLRGLGGLLLRRGRLRGLGLLLLLLRLRRLGGRRGLLGRGRGLRRRRRRGLLRGRLLGGGRLLGGLRGLLLLRLLRLLLGLLLLGGGGRLRGLGLRRRLRGLLRRRLLRLGRLLLRRLLLLLRRRLGLLRLRRRGGGRLGLGRLGGLGRLLRRLGLGLLGLLRLRRLRLLRRGRLGLRLRLGRGRLLLGRGGRGLLLLRGLRRGRLLLGRLRRRLRGGLLLRLLRLLGRLGRRGGRRLLLRRLGGRLLLLLLRRGGRLRLRLRLLLRLLRGLRLRRRLRRGLLGRGLRRRRRRLRGRLGGRRLGLLGRRRLLLGRRGRGLLRRLGGLRLRLLLLGGRGLGGLLRLGRLLRLLLLGRRRLRRGLLRRRRGRGRLGRLLRRRLLRRRLRRGGLRLRLLRGLLRRLRLLLLRRRRLLLLLLGGLGRRRRLRRLLRLGLGLRLRGLLGGLGLLRRGGLRLLLLLLLGLRLLLLLLLRRLRRRGLGLGLGLLLRRLGLLGRLRLGRRLLLRRRLLRRGRLRGLRRLRRGLRLLLLRGRRRRLLRLLGRLGRGRRLLLRRRRLLLRRLRLRGRLLRGRGLGGRLRLRRRRRRLLGGLRLGLLLLGGRGRLLLLRGLGGRRLRLLRRGLLRLRGGLLRRRLGRLLLLLLLRRRRLGLLRRGRLLGRRRLLRLLGGLLLRLRLLLGRGLLLRLGLGRRLGLGGGRGGLRRRLRGRGRLLRRLRGRLRRGGLRRGRGLLGGGRRRLGGGRGRRGGRRRLRLLRRGGRRLLRRRLRLRLRLGRLRRLRGLLLLLLRRGGRGRRLLRLLLLRRLLLRRRRGGLLRLRLRGRLLLGRLRLRLLLRRLRGLLLGGRLRLRRLGRGRRRGLGGGRLGRRGGRLLLRRGRGLLRLRRRRLLLLRLRRLGRGLRLRRRRRRRRLRLLLRLLGLRRLLLLLRLRGRGRRLRLRGLRLLLRLRRGLGRLRRGLLGGLRLRGLLLLGGRLLLLLLLLRGRGLLLLRLGLLGGLRLLLLRGRGRLLGLLLRRGRLRLRRRRGGRRRRRGLGLRLLRGLRRLLGLLGRLLRLRGLLGRLLGGRLRGRGGRGGRGGRLLLRLRRLRGLLGGLLGRLGLLRLGLLRGLRGRRGGRRLRGLLGLRLGRLLRLLGRRRLRGLGLRLRGRLGRLLGGRRGRLGGLGLLLRLLGRGLGGRLGRGLGRRRRRRLRRGLLRGLRLGRRRLGRRLRLGRRRLLGLLLGGGLLRRLLLRRRLRLLLRLLLRLRLGLLRLLRLRLRLRLLLRRRGRLGRLLLLRLLRRLRRLRGGLRLRLLLLLRLRLGRLRLLLLLRRRGRRLLLLLRRLGRRRRLLRRGGLRLRRGLRLRRGLLGLRRLRRLRLLLGLGLGRLRLGLRLLLLRLRRGLGGLGLGLGRLGLLRLRRGRLRLRLGRGGGGLLLLLLRLRGRRLLLGLGLRLLLLRRLRRRLRLLLLRRLRRRLLLRLGRLLRLGLRLLLRLRLRGLLRRGLGGLLRLLLGRRLRLLRGLRRRGRRRLRGLRRRLLRGRRLLLRLLR']))